"""Independent literals for the PA taper band-coordinate regression.

The expected amounts are worked from taxable income, not generated by a
second implementation:
  PA = 12,570 - max(0, ANI - 100,000) / 2
  taxable income = gross income - PA
  first 37,700 taxable at 20%; remainder to 125,140 at 40%; then 45%.
"""
from decimal import Decimal as D

from reserved.engines.income_tax import _personal_allowance, _total_income_tax
from reserved.engines.tax_config import get_config


CFG = get_config("2026/27")


def test_full_taper_range_literal_totals():
    expected = {
        "99999": "27431.60",
        "100000": "27432.00",
        "100001": "27432.60",
        "110000": "33432.00",
        "112570": "34974.00",
        "125139": "42515.40",
        "125140": "42516.00",
        "125141": "42516.45",
        "130000": "44703.00",
    }
    for income, tax in expected.items():
        assert _total_income_tax(D(income), D("0"), CFG) == D(tax)


def test_allowance_boundaries_are_not_rounded_to_whole_pounds():
    expected = {
        "99999": "12570",
        "100000": "12570",
        "100001": "12569.5",
        "112570": "6285",
        "125139": "0.5",
        "125140": "0",
        "125141": "0",
    }
    for ani, allowance in expected.items():
        assert _personal_allowance(D(ani), CFG) == D(allowance)


def test_each_pound_inside_taper_has_sixty_percent_income_tax_effect():
    for start in ("100000", "100001", "110000", "112570", "125139"):
        before = _total_income_tax(D(start), D("0"), CFG)
        after = _total_income_tax(D(start) + D("1"), D("0"), CFG)
        assert after - before == D("0.60")


def test_first_pound_above_taper_is_additional_rate_only():
    assert (
        _total_income_tax(D("125141"), D("0"), CFG)
        - _total_income_tax(D("125140"), D("0"), CFG)
        == D("0.45")
    )


def test_pension_and_ani_interactions_across_taper():
    expected = {
        # (income, gross RaS pension): (ANI, PA, total income tax)
        ("110000", "0"): ("110000", "7570", "33432.00"),
        ("110000", "1"): ("109999", "7570.5", "33431.60"),
        ("110000", "10000"): ("100000", "12570", "29432.00"),
        ("110000", "10001"): ("99999", "12570", "29431.80"),
        ("125140", "25140"): ("100000", "12570", "32460.00"),
        ("125141", "25140"): ("100001", "12569.5", "32460.60"),
    }
    for (income, pension), (ani, allowance, tax) in expected.items():
        actual_ani = max(D("0"), D(income) - D(pension))
        assert actual_ani == D(ani)
        assert _personal_allowance(actual_ani, CFG) == D(allowance)
        assert _total_income_tax(D(income), D(pension), CFG) == D(tax)


def test_ten_thousand_pension_at_110k_reduces_income_tax_by_four_thousand():
    before = _total_income_tax(D("110000"), D("0"), CFG)
    after = _total_income_tax(D("110000"), D("10000"), CFG)
    assert before - after == D("4000.00")

